create table if not exists suggestions (
  race_id text primary key,
  venue text not null,
  race_number integer not null,
  category text not null,
  country text not null,
  start_time timestamptz not null,
  logged_at timestamptz not null,
  tag text not null,
  pick_number integer not null,
  pick_name text not null,
  price double precision,
  favourite_number integer,
  favourite_name text,
  favourite_price double precision,
  ranking jsonb not null default '[]'::jsonb,
  market_order jsonb not null default '[]'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  concerns jsonb not null default '[]'::jsonb,
  model jsonb,
  field jsonb not null default '[]'::jsonb,
  outcome text not null default 'pending',
  result_kind text,
  result_source text,
  winner_number integer,
  winner_name text,
  pick_position integer,
  placings jsonb not null default '[]'::jsonb,
  miss_reason text,
  next_time text,
  feed jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists suggestions_logged_at_idx on suggestions (logged_at desc);
